<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
        <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="input-box">
        <h3>Delivery At</h3>
        <input type="text" id="deliveryat" name="delivery_date" class="input-text"/>
        <img title="Select date" id="delivCalendar" src="<?php echo $this->getSkinUrl('images/calendar.gif'); ?>"
             class="v-middle">
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;">
                <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingMethod.save()">
            <span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                 alt="<?php echo $this->__('Loading next step...') ?>"
                 title="<?php echo $this->__('Loading next step...') ?>"
                 class="v-middle"/> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    Calendar.setup({
        inputField: 'deliveryat',
        ifFormat: '%m/%e/%y',
        button: 'delivCalendar',
        singleClick: true,
        disableFunc: function (date) {
            var now = new Date();
            if ((date - now) < 0) {
                return true;
            } else {
                return false;
            }
        }
    });
    //]]>
</script>