<!--<h2><a href="--><?php //echo Mage::getUrl('news/index/index'); ?><!--">News</a></h2>-->
<?php echo $this->getChildHtml('news.title'); ?>

<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
?>
<?php foreach ($news as $item): ?>
    <div>
        <h2>
            <a href="<?php echo $newsViewUrl; ?>?id=<?php echo $item->getId(); ?>">
                <?php echo $item->getTitle(); ?>
            </a>
        </h2>
        <p>
            <?php echo $item->getAnnounce(); ?>
        </p>
    </div>
<?php endforeach; ?>