<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
?>
<?php if (count($news) !== 0): ?>
    <h2><a href="<?php echo Mage::getUrl('news/index/index'); ?>">News</a></h2>
<?php endif; ?>
<?php //echo $this->getChildHtml('news.title'); ?>


<?php foreach ($news as $item): ?>
    <div>
        <h2>
            <a href="<?php echo $newsViewUrl; ?>?id=<?php echo $item->getId(); ?>">
                <?php echo $item->getTitle(); ?>
            </a>
        </h2>

        <p>
            <?php echo $item->getAnnounce(); ?>
        </p>
    </div>
<?php endforeach; ?>