<?php
?>

<?php if (!$this->checkUserNewstoreMember()): ?>

    <div id="messages"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
    <?php echo $this->getChildHtml('global_messages') ?>
    <form action="<?php echo $this->getUrl('newstoremembers/number/cart') ?>" method="post" id="form-validate"
          autocomplete="off">
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Newstore Members') ?></h2>
            <ul class="form-list">
                <li>
                    <label for="email" class="required"></label>
                    <label class="required">
                        <?php echo $this->__('Number') ?>
                        <input type="text" name="number" id="number" value="" title=""
                               class="input-text required-entry"/>
                    </label>
                </li>
            </ul>
            <div class="buttons-set">
                <p class="back-link">
                    <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                        <small>&laquo; </small><?php echo $this->__('Back') ?>
                    </a>
                </p>
                <button type="submit" title="<?php echo $this->__('Save') ?>" class="button">
                    <span><span><?php echo $this->__('Save') ?></span></span>
                </button>
            </div>
        </div>
    </form>
<?php endif; ?>
