<?php

class ISM_NewstoreMembers_Block_Number extends Mage_Core_Block_Template
{

//    protected function _prepareLayout()
//    {
//        parent::_prepareLayout(); // TODO: Change the autogenerated stub
//        /** @var Mage_Core_Block_Template $block */
////        $block = $this->getLayout()->addBlock('core/template', 'news.title');
////        $block->setTemplate('news/widget/title.phtml');
////        $this->setChild('news.title', $block);
//
//    }
//    protected function _beforeToHtml()
//    {
//        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
//    }
}