<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
?>
    <h1>News</h1>
<?php foreach ($news as $item): ?>
    <div>
        <h2>
            <a href="<?php echo $newsViewUrl; ?>?id=<?php echo $item->getId(); ?>">
                <?php echo $item->getTitle(); ?>
            </a>
        </h2>
        <p>
            <?php echo $item->getAnnounce(); ?>
        </p>
    </div>
<?php endforeach; ?>